apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-collector
  namespace: analytics-collector
  labels:
    app: analytics-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-collector
  template:
    metadata:
      labels:
        app: analytics-collector
    spec:
      automountServiceAccountToken: false
      containers:
        - name: analytics-collector
          image: analytics-collector
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 8001
          envFrom:
            - secretRef:
                name: analytics-collector
          resources:
            limits:
              memory: 128M
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
