apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: analytics-collector
    newName: ghcr.io/corybuecker/analytics-collector
    digest: sha256:2b66fc19935401eaccb1eb4343cb2e620a713e7ebbcef57e0ddbc043cbe661b4

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

secretGenerator:
  - name: analytics-collector
    namespace: analytics-collector
    envs:
      - .env
