apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: analytics-collector
    newName: ghcr.io/corybuecker/analytics-collector
    digest: sha256:ec8f32ec251bf68747729da731a75efd08e005f94ddd3df96053aa97cf1c8ac2

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - service-account.yaml

secretGenerator:
  - name: analytics-collector
    namespace: analytics-collector
    envs:
      - .env

patches:
  - path: ./patches/deployment.yaml
    target:
      kind: Deployment
