apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: analytics-collector
    newName: ghcr.io/corybuecker/analytics-collector
    digest: sha256:ca3052ba4dca23d3bfed60db6820a3c999792ce5245d111b1423b11d73dc6b80

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - service-account.yaml

secretGenerator:
  - name: analytics-collector
    namespace: analytics-collector
    envs:
      - .env

patches:
  - path: ./patches/deployment.yaml
    target:
      kind: Deployment
