apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: analytics-collector
    newName: ghcr.io/corybuecker/analytics-collector
    digest: sha256:2be40953eb228b4b43af2ada0b53893cb33bdfc5025f504e0129b7db238681ac

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - service-account.yaml

secretGenerator:
  - name: analytics-collector
    namespace: analytics-collector
    envs:
      - .env

patches:
  - path: ./patches/deployment.yaml
    target:
      kind: Deployment
