apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: analytics-collector
    newName: ghcr.io/corybuecker/analytics-collector
    digest: sha256:e714c0a4d5d65bb9f94b472bf9ed5a5ffaae6b7dfd5375fe00e1fea044e7a690

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

secretGenerator:
  - name: analytics-collector
    namespace: analytics-collector
    envs:
      - .env
